---
- name: Add postgresql-11 repo
  yum:
    name: https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
- name: Install postgresql-11
  yum:
    name:
      - postgresql11-server
      - postgresql11
- name: Init postgres db
  shell: /usr/pgsql-11/bin/postgresql-11-setup initdb
  ignore_errors: yes

- name: Copy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/11/data/postgresql.conf
- name: Copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/11/data/pg_hba.conf
    backup: yes
  #notify: restart postgres
- name: Restart postgresql
  shell: systemctl restart postgresql-11; systemctl enable postgresql-11
- name: Create zabbix user
  shell: psql -U postgres -c "create user {{ zabbix_db_user }} with password '{{ zabbix_db_password }}'"
  ignore_errors: yes
- name: Create zabbix DB
  shell: sudo -u postgres createdb -O "{{ zabbix_db_user }}" "{{ zabbix_db_name }}" --encoding='utf-8'
  ignore_errors: yes

